version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
    - run:
        name: Install
        command: |
          sudo pip install pylint
    - run:
        name: Run pylint
        command: pylint ./thing
    - run:
        name: Reveal a terrible secret
        command: echo $SECRET_VARIABLE
