version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Install
        command: |
          sudo pip install pylint
    - run:
        name: Run pylint
        command: pylint ./thing
